on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        id: deploy
        uses: helloitsjoe/deploy-github-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
